- src/main/java/com/four/brothers/runtou/RuntouApplication.java
- src/main/java/com/four/brothers/runtou/domain/Admin.java
- src/main/java/com/four/brothers/runtou/domain/ChatMessage.java
- src/main/java/com/four/brothers/runtou/domain/ChatRoom.java
- src/main/java/com/four/brothers/runtou/domain/FilterWord.java
- src/main/java/com/four/brothers/runtou/domain/Match.java
- src/main/java/com/four/brothers/runtou/domain/MatchRequest.java
- src/main/java/com/four/brothers/runtou/domain/OrderSheet.java
- src/main/java/com/four/brothers/runtou/domain/OrderSheetCategory.java
- src/main/java/com/four/brothers/runtou/domain/Orderer.java
- src/main/java/com/four/brothers/runtou/domain/Performer.java
- src/main/java/com/four/brothers/runtou/domain/Report.java
- src/main/java/com/four/brothers/runtou/domain/ReportCategory.java
- src/main/java/com/four/brothers/runtou/domain/Review.java
- src/main/java/com/four/brothers/runtou/domain/ReviewScore.java
- src/main/java/com/four/brothers/runtou/domain/User.java
- src/main/java/com/four/brothers/runtou/domain/base/BaseTimeEntity.java
- src/main/java/com/four/brothers/runtou/repository/user/AdminRepository.java
- src/main/java/com/four/brothers/runtou/repository/user/OrdererRepository.java
- src/main/resources/application.properties
- 엔티티 설계
- 모든 엔티티 설계 완료
- 기본 Orderer Repository 작성완료
- 기본 Admin Repository 작성완료
> 엔티티 설계 및 기본 Repository 클래스 추가

- src/main/java/com/four/brothers/runtou/config/SwaggerConfig.java
SecurityScheme.In.COOKIE가 올바른 방식이므로 변경함.
> Fix: SecurityScheme In 변경

- src/main/java/com/four/brothers/runtou/config/SwaggerConfig.java
빈을 등록하는 클래스이므로,
@Configuration 애너테이션을 쓰는 것이 바람직함.
> Fix: Swagger 설정 수정

- build.gradle
- src/main/java/com/four/brothers/runtou/config/WebSecurityConfig.java
- src/main/java/com/four/brothers/runtou/service/UserService.java
- src/test/java/com/four/brothers/runtou/etc/PasswordEncoderTest.java
- 사용자 패스워드 암호화 기능 추가함.
- 회원가입 시, DB엔 암호화된 사용자의 비밀번호가 추가되도록 수정함.
- 테스트 코드 작성 완료함.
> 패스워드 암호화(인코딩) 적용

- src/main/java/com/four/brothers/runtou/domain/User.java
> Fix: 회원 비밀번호 Column 길이 제한 해제

- src/main/resources/application.properties
로컬에서 빌드 시, 직접 VM Argument를 설정하도록 수정함.
> Fix: local 환경 properties 파일 active 삭제

- src/main/java/com/four/brothers/runtou/controller/AdminController.java
- src/main/resources/templates/db-main.html
- src/main/resources/templates/db-table-not-show.html
- src/main/resources/templates/db-table.html
> Fix: 어드민용 DB 접근 Endpoint 변경

- build.gradle
> Fix: javax.annotation.meta.When 오류 해결

- build.gradle
Gradle 빌드 시, 또 다른 문제가 야기되어
다시 복구함.
> Fix: javax.annotation.meta.When 오류 복구

- src/main/java/com/four/brothers/runtou/config/LoginConfig.java
- src/main/java/com/four/brothers/runtou/interceptor/NoHandlerFoundInterceptor.java
> 404 및 401 오류 처리 범위 정상화

- src/main/java/com/four/brothers/runtou/controller/AdminController.java
> fix #29 - 어드민 db 확인 페이지 redirect 수정

- src/main/java/com/four/brothers/runtou/controller/UserRestController.java
- src/main/java/com/four/brothers/runtou/exception/BadRequestException.java
- src/main/java/com/four/brothers/runtou/exception/code/ExceptionCode.java
- src/main/java/com/four/brothers/runtou/exception/code/LoginExceptionCode.java
- src/main/java/com/four/brothers/runtou/exception/code/RequestExceptionCode.java
- src/main/java/com/four/brothers/runtou/exception/code/SignupExceptionCode.java
> 중복 정보로 회원가입 시, 500 에러 응답되는 이슈 해결

- src/main/java/com/four/brothers/runtou/domain/FilterWord.java
- src/main/java/com/four/brothers/runtou/repository/user/FilterWordRepository.java
> FilterWord 레파지토리 저장 메서드 추가

- src/main/java/com/four/brothers/runtou/repository/user/FilterWordRepository.java
> fix #36 - Issue Fix

- src/test/java/com/four/brothers/runtou/repository/user/FilterWordRepositoryTest.java
> Test : filterWordTest done

- src/test/java/com/four/brothers/runtou/repository/user/AdminRepositoryTest.java
- src/test/java/com/four/brothers/runtou/repository/user/FilterWordRepositoryTest.java
> Refatoring Test Codes

- src/main/java/com/four/brothers/runtou/repository/user/MatchingRepository.java
> Feat: Matching save 메서드 추가

- src/main/java/com/four/brothers/runtou/repository/user/OrdererRepository.java
- src/test/java/com/four/brothers/runtou/repository/user/OrdererRepositoryTest.java
> Test: OrdererRepositoryTest done

- src/main/java/com/four/brothers/runtou/controller/OrderSheetRestController.java
- src/main/java/com/four/brothers/runtou/controller/advice/ControllerAdvice.java
- src/main/java/com/four/brothers/runtou/domain/OrderSheetCategory.java
- src/main/java/com/four/brothers/runtou/dto/OrderSheetDto.java
- src/main/java/com/four/brothers/runtou/dto/model/OrderSheetDto.java
- src/main/java/com/four/brothers/runtou/repository/user/OrderSheetRepository.java
- src/main/java/com/four/brothers/runtou/service/OrderSheetService.java
- 요청서 등록 API
- 요청서 목록 조회 API
- 요청서 상세 조회 API
위 3가지 API 작성 완료됨.
> 요청서 추가·조회 로직 추가

- src/main/java/com/four/brothers/runtou/config/LoginConfig.java
- src/main/java/com/four/brothers/runtou/controller/OrderSheetRestController.java
- src/main/java/com/four/brothers/runtou/controller/TestRestController.java
- src/main/java/com/four/brothers/runtou/domain/OrderSheet.java
- src/main/java/com/four/brothers/runtou/service/OrderSheetService.java
- 주문서 결제 상태를 변환시키는 테스트용 API를 추가함.
> 테스트용 컨트롤러 추가

- src/main/java/com/four/brothers/runtou/controller/OrderSheetRestController.java
- src/main/java/com/four/brothers/runtou/controller/UserRestController.java
- src/main/java/com/four/brothers/runtou/controller/advice/ControllerAdvice.java
- src/main/java/com/four/brothers/runtou/domain/OrderSheet.java
- src/main/java/com/four/brothers/runtou/dto/ErrorDto.java
- src/main/java/com/four/brothers/runtou/exception/BadRequestException.java
- src/main/java/com/four/brothers/runtou/exception/Exception.java
- src/main/java/com/four/brothers/runtou/exception/NoAuthorityException.java
- src/main/java/com/four/brothers/runtou/exception/code/OrderSheetExceptionCode.java
- src/main/java/com/four/brothers/runtou/exception/code/RequestExceptionCode.java
- src/main/java/com/four/brothers/runtou/repository/user/OrderSheetRepository.java
- src/main/java/com/four/brothers/runtou/service/OrderSheetService.java
- 요청서 수정 API 구현 완료함.
- 오류(예외)에 대한 상세정보도 함께 응답하도록 추가함.
> 요청서 수정 및 오류 디테일 정보 추가

- src/test/java/com/four/brothers/runtou/repository/user/PerformerRepositoryTest.java
> Test : PerformerRepositoryTest done

- src/main/java/com/four/brothers/runtou/repository/user/OrderSheetRepository.java
> Feat: findAllOnlyPayed 메서드 매개변수 null 허용 명시

- src/main/java/com/four/brothers/runtou/repository/user/UserRepository.java
- UserRepository 저장 메서드 추가
- 메서드 설명 주석 추가
> UserRepository 저장 메서드 추가

- src/test/java/com/four/brothers/runtou/repository/user/ReviewRepositoryTest.java
> Test : ReviewRepositoryTest done

- src/test/java/com/four/brothers/runtou/repository/user/ReportRepositoryTest.java
> Test : ReportRepositoryTest-ck done

- src/main/java/com/four/brothers/runtou/domain/Orderer.java
- src/main/java/com/four/brothers/runtou/repository/user/OrdererRepository.java
- src/test/java/com/four/brothers/runtou/repository/user/MatchRequestRepositoryTest.java
- src/test/java/com/four/brothers/runtou/repository/user/OrderSheetRepositoryTest.java
- src/test/java/com/four/brothers/runtou/repository/user/OrdererRepositoryTest.java
> Order sheet repository test ck

- src/main/java/com/four/brothers/runtou/domain/MatchRequest.java
- src/main/java/com/four/brothers/runtou/domain/Matching.java
- src/main/java/com/four/brothers/runtou/domain/OrderSheet.java
- src/main/java/com/four/brothers/runtou/dto/model/MatchRequestDto.java
- src/main/java/com/four/brothers/runtou/repository/user/MatchRequestRepository.java
- src/test/java/com/four/brothers/runtou/repository/user/MatchRequestRepositoryTest.java
> Fix: MatchRequest, Match, OrderSheet 엔티티 연관관계 수정

- src/main/java/com/four/brothers/runtou/controller/UserRestController.java
- src/main/java/com/four/brothers/runtou/dto/AdminDto.java
- src/main/java/com/four/brothers/runtou/service/UserService.java
- src/test/java/com/four/brothers/runtou/service/UserServiceTest.java
> User service test taegyun

- src/main/java/com/four/brothers/runtou/controller/ChatController.java
- src/main/java/com/four/brothers/runtou/controller/ChatRoomRestController.java
- src/main/java/com/four/brothers/runtou/controller/MatchingController.java
- src/main/java/com/four/brothers/runtou/controller/SocketController.java
- src/main/java/com/four/brothers/runtou/domain/MatchRequest.java
- src/main/java/com/four/brothers/runtou/domain/Performer.java
- src/main/java/com/four/brothers/runtou/dto/MatchRequestDto.java
- src/main/java/com/four/brothers/runtou/dto/MatchingDto.java
- src/main/java/com/four/brothers/runtou/dto/model/MatchRequestDto.java
- src/main/java/com/four/brothers/runtou/exception/code/MatchRequestExceptionCode.java
- src/main/java/com/four/brothers/runtou/repository/ChatRoomRepository.java
- src/main/java/com/four/brothers/runtou/repository/MatchRequestRepository.java
- src/main/java/com/four/brothers/runtou/repository/MatchingRepository.java
- src/main/java/com/four/brothers/runtou/service/ChatRoomService.java
- src/main/java/com/four/brothers/runtou/service/ChatService.java
- src/main/java/com/four/brothers/runtou/service/MatchRequestService.java
- src/main/java/com/four/brothers/runtou/service/MatchingService.java
- 이슈 #85 수정
- 이슈 #84 수정
- 기타 리팩토링
> 매칭 요청 관련 버그 수정 및 리팩토링

- src/main/java/com/four/brothers/runtou/controller/MatchingController.java
- src/main/java/com/four/brothers/runtou/domain/Matching.java
- src/main/java/com/four/brothers/runtou/dto/MatchingDto.java
- src/main/java/com/four/brothers/runtou/dto/model/MatchingDto.java
- src/main/java/com/four/brothers/runtou/exception/code/MatchingExceptionCode.java
- src/main/java/com/four/brothers/runtou/repository/MatchingRepository.java
- src/main/java/com/four/brothers/runtou/service/MatchRequestService.java
- src/main/java/com/four/brothers/runtou/service/MatchingService.java
- src/test/java/com/four/brothers/runtou/repository/MatchingRepositoryTest.java
- src/test/java/com/four/brothers/runtou/repository/ReviewRepositoryTest.java
- 심부름 수행 완료 후, 심부름 요청자에게 알리는 API를 추가함.
- 이슈 #87 수정.
> 심부름 수행 완료 요청 API 추가 및 버그 수정

- src/main/java/com/four/brothers/runtou/domain/ChatRoom.java
- src/main/java/com/four/brothers/runtou/repository/ChatRoomRepository.java
> Fix: 채팅방 삭제 시, 관련 메시지까지 삭제하도록 수정

- src/main/java/com/four/brothers/runtou/domain/Admin.java
- src/main/java/com/four/brothers/runtou/domain/ChatMessage.java
- src/main/java/com/four/brothers/runtou/domain/ChatRoom.java
- src/main/java/com/four/brothers/runtou/domain/FilterWord.java
- src/main/java/com/four/brothers/runtou/domain/MatchRequest.java
- src/main/java/com/four/brothers/runtou/domain/Matching.java
- src/main/java/com/four/brothers/runtou/domain/OrderSheet.java
- src/main/java/com/four/brothers/runtou/domain/Orderer.java
- src/main/java/com/four/brothers/runtou/domain/Performer.java
- src/main/java/com/four/brothers/runtou/domain/Report.java
- src/main/java/com/four/brothers/runtou/domain/User.java
> Fix: 엔티티 AllArgsConstructor

- src/main/java/com/four/brothers/runtou/domain/Admin.java
- src/main/java/com/four/brothers/runtou/domain/Orderer.java
- src/main/java/com/four/brothers/runtou/domain/Performer.java
- src/main/java/com/four/brothers/runtou/domain/User.java
> Fix: 엔티티 id 필드 채울 수 있는 생성자 추가

- src/main/java/com/four/brothers/runtou/controller/OrderSheetRestController.java
- src/main/java/com/four/brothers/runtou/exception/code/PointExceptionCode.java
- src/main/java/com/four/brothers/runtou/service/MatchingService.java
- src/main/java/com/four/brothers/runtou/service/OrderSheetService.java
- 요청서 등록시, 포인트 사용
- 매칭 업무 완료시, 포인트 획득
> 포인트 제도 도입 완료

- src/main/java/com/four/brothers/runtou/dto/CostDto.java
- src/main/java/com/four/brothers/runtou/service/CostRecommendService.java
- 입력된 거리가 '-1'인 경우, 0.6으로 가중치 할당
> Feat: 가격 추천시, 임시 거리 값 추가

- src/test/java/com/four/brothers/runtou/integretion/UserIntegrationTest.java
> User integretion test ck
